os:
  - linux
  - osx
language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - node
  - lts/boron
  - lts/carbon
  - lts/dubnium
  - lts/erbium
  - lts/*
install: npm install
before_script:
  - "npm install -g grunt-cli"
  - "grunt build"
after_success:
  - ./node_modules/.bin/istanbul report text-summary lcov
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
