# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 9.x, 10.x, 11.x, 12.x, 13.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm version
    - run: npm ci || npm install
    - run: npm run build
    - run: npm test
    - run: npm run coverage
      env:
        COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
        COVERALLS_SERVICE_NAME: "gh-actions"
        COVERALLS_SERVICE_NUMBER: "${{ github.run_id }}:${{ github.run_number }}"
        COVERALLS_GIT_BRANCH: "${{ github.ref }}"
        COVERALLS_PARALLEL: "true"
        COVERALLS_GIT_COMMIT: "HEAD"
